### PR TITLE
feat(User): Find user in DB by mail & ValidatePassword + fixes

### PR DESCRIPTION
**Pull request by KaruzG**
###  read(_string: userEmail_)
With the method (read) you give an email parameter and finds the user.
image

image

.

###  validatePassword(_string: password, string: userEmail_)
Returns true or false if the password is correct or not
image

.

### create()
create() now encrypts the password! 🔐

> Fixes:
> - Some problems with the readRecord from Database
> - Returns of empty query

### CODE REVIEW

**Review by JME469 — APPROVED** [review]
Got it!

**Comment by KaruzG** [comment]
If PR is in draft you dont need to review it ;)

Now its ready!

**Review by JME469 — APPROVED** [review]
:thumbsup: :thumbsup:

**Review by Rafval18 — APPROVED** [review]
Good Job

**Pull request merged**
