### PR TITLE
Users backend (login and register)

### PR DESCRIPTION
**Pull request by JME469**
Both register and login should work fine, let me know if is there any issues

### CODE REVIEW

**Review by Rafval18 — APPROVED** [review]
ok Good Job!

**Comment by KaruzG** [comment]
image

I cant make this work, every query to the DB from the login/register gives an error

PD: Im going to edit some pathings

**Comment by JME469** [comment]
I have been looking for syntax errors in the php files and I can't find the issue, looks like the paths are correct, the queries were working yesterday before updating the branch, may that be the cause for invisible conflicts or so. However im still testing and working on it too, let me know if there are any advances. @KaruzG

**Comment by KaruzG** [comment]
This is the only thing I found that could be interfering. I will check later if you used that method for something

image

**Comment by JME469** [comment]
I kind of fixed the query issue we were having, I binded the parameter used in the query, now the users are created in database successfully. 

However, the script shows the "Account existent" error instead of showing the success page. Seems like if the create function was triggered twice. 

Test it and tell me if the user creation works for you, and if you have any fixes for the redirection after. I proceed to test login/session now.

fix

**Comment by KaruzG** [comment]
> fix

You should adapt you code to the method. Or adapt the method. But there are some features in main using that $condition parameter... I tested the branch and I fixed some things but this change in the readRecord function breaks many feats in main

**Comment by KaruzG** [comment]
Im going to finish the reDesign branch and after that I will continue fixing this one

**Comment by KaruzG** [comment]
# Login and register fixed

New feats also (sorry for not branching this, I needed the logger for fixing this branch)
### Logger:
Logs things 
image

### UserInfo:
image


@JME469 Comment if you approve this merge :)

**Review by KaruzG — APPROVED** [review]

**Comment by JME469** [comment]
It's great!! Merge approved 👍🏼

**Pull request merged**
